channelList = [
    {
        user:"TWR01",
        trigram: "G12C8",
        interval: 30000,
        nInterval: 3,
        outChannel: "TWR02",
        intMail: "bgomez@newtech.net;mesacontrol@newtech.net",
        outMail: "ch01@cliente.com",
        priority: 1,
        maxSize: 2000,
        custom: false,
        fileName: "EVTWPAN;TowerBank_MCI;",
        vsKeys: "TWRVS",
        mcKeys: "TWRMC"
    },
    {
        user:"BANDEL01",
        trigram: "G13B6",
        interval: 60000,
        nInterval: 5,
        outChannel: "BANDEL01",
        intMail: "mesacontrol_pty@newtech.net",
        outMail: "ch02@cliente.com",
        priority: 1,
        maxSize: 10000,
        custom: false,
        fileName: "BDELPURE_;DX_BDELPURE_",
        vsKeys: "BDELPURE",
        mcKeys: ""
    },
    {
        user:"COOPED01",
        trigram: "G1397",
        interval: 60000,
        nInterval: 5,
        outChannel: "COOPED01",
        intMail: "mesacontrol_pty@newtech.net",
        outMail: "ch02@cliente.com",
        priority: 1,
        maxSize: 10000,
        custom: false,
        fileName: "COOPED01_;DX_COOPED01_",
        vsKeys: "COOPED01",
        mcKeys: ""
    },
    {
        user:"BNC03",
        trigram: "G09D0",
        interval: 60000,
        nInterval: 5,
        outChannel: "BNC04",
        intMail: "bgomez@newtech.net;mesacontrol_pty@newtech.net",
        outMail: "ch03@cliente.com",
        priority: 2,
        maxSize: 10000,
        custom: false,
        fileName: "CLOSTER_;",
        vsKeys: "BNCVS",
        mcKeys: "BNCMC"
    },
    {
        user:"CH04",
        trigram: "TRI02",
        interval: 60000,
        nInterval: 10,
        outChannel: "",
        intMail: "bgomez@newtech.net;mesacontrol_pty@newtech.net",
        outMail: "ch04@cliente2.com",
        priority: 2,
        maxSize: 10000,
        custom: false,
        fileName: " ;",
        vsKeys: "",
        mcKeys: ""
    },
    {
        user:"CH05",
        trigram: "TRI05",
        interval: 60000,
        nInterval: 5,
        outChannel: "",
        intMail: "mesacontrol_pty@newtech.net",
        outMail: "ch05@cliente20.com",
        priority: 2,
        maxSize: 10000,
        custom: false,
        fileName: " ;",
        vsKeys: "",
        mcKeys: ""
    },
] 

module.exports = channelList;